name: check-pr

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          npm install -g yarn
          chmod +x scripts/build.sh
          chmod +x scripts/deploy.sh
          scripts/build.sh
      - name: Build WLE Project
        run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project tests/wonderland/wonderland-test.wlp --output tests/wonderland/deploy/ --credentials $WLE_CREDENTIALS
        env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
      - name: Test
        run: |
          cd ~/work/ads-sdk/ads-sdk
          npx playwright install
          yarn run test
